"""Increase charcount limit for response

Revision ID: bdde99086d78
Revises: 30246447a74a
Create Date: 2025-05-08 14:36:00.356886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdde99086d78'
down_revision: Union[str, None] = '30246447a74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsed_response', 'raw_text',
               existing_type=sa.VARCHAR(length=15000),
               type_=sa.String(length=20000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parsed_response', 'raw_text',
               existing_type=sa.String(length=20000),
               type_=sa.VARCHAR(length=15000),
               existing_nullable=False)
    # ### end Alembic commands ###
